Repository kookmin-sw/capstone-2023-06, pull requests merged in 2023-05, with the labels that each got.

#22 feat: Product
  client/src/components/common/Button.tsx
  client/src/components/common/Input.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlockReadonly.tsx
  client/src/components/product/Comment.tsx
  client/src/components/product/ProductCard.tsx
  client/src/components/product/ProductComment.tsx
  client/src/components/product/ProductDetailPost.tsx
  client/src/pages/Product.tsx
  client/src/styles/GlobalStyle.jsx
  client/src/type/product.ts
Labels: 새 기능, 프론트엔드

#26 Issue/add user info
  server/src/controller/post_controller.js
  server/src/model/post_model.js
  server/src/model/postcomments_model.js
  server/src/model/postlikes_model.js
Labels: 백엔드

#28 feat: main 컴포넌트, 광고배너
  client/src/components/common/Button.tsx
  client/src/components/common/Grid.tsx
  client/src/components/common/Nav.tsx
  client/src/components/layout/Footer.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/main/adbanner/AdBanner.styles.tsx
  client/src/components/main/adbanner/AdBanner.tsx
  client/src/components/main/adbanner/AdIndicator.tsx
  client/src/components/main/adbanner/AdSlide.tsx
  client/src/components/main/adbanner/AdStyles.tsx
  client/src/components/main/postbanner/Thumbnail.styles.tsx
  client/src/components/main/postbanner/Thumbnail.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  npm@1.0.0
  package-lock.json
  package.json
Labels: 새 기능, 프론트엔드

#25 feat: Review 컴포넌트
  client/package-lock.json
  client/package.json
  client/src/components/Review.tsx
  client/src/components/product/ProductReview.tsx
  client/src/components/profile/ProfileBar.tsx
  client/src/pages/Post.tsx
  client/src/pages/Product.tsx
  client/tsconfig.json
Labels: 새 기능, 프론트엔드

#34 fix: 메인 페이지에서 MainPost 컴포넌트 -> Review 컴포넌트
  client/src/components/Review.tsx
  client/src/components/product/ProductReview.tsx
  client/src/components/profile/ProfileBar.tsx
  client/src/pages/Main.tsx
  package-lock.json
Labels: 프론트엔드

#36 feat: Post 에 Comment 들 API 연결
  client/src/api/upload.ts
  client/src/components/Comment/CommentList.tsx
  client/src/components/Comment/index.tsx
  client/src/components/common/Grid.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlockReadonly.tsx
  client/src/components/product/ProductCard.tsx
  client/src/components/product/ProductComment.tsx
  client/src/pages/Main.tsx
  client/src/pages/Post.tsx
  client/src/pages/Product.tsx
  client/src/type/product.ts
Labels: 새 기능, 프론트엔드

#43 Hotfix/followr and product
  server/database/sql/init/05_init_products.sql
  server/package-lock.json
  server/package.json
  server/src/controller/product_controller.js
  server/src/index.js
  server/src/model/product_model.js
  server/src/routes/product_routes.js
  server/src/routes/user_routes.js
  server/src/test/api/follower.test.js
  server/src/test/api/product.test.js
  server/src/test/api/productComment.test.js
  server/src/test/api/productLikes.test.js
Labels: 버그, 백엔드

#44 feat: 작성시 검색 modal 띄우기 & 제품 modal 띄우기
  client/src/App.tsx
  client/src/api/product.ts
  client/src/api/upload.ts
  client/src/api/users.ts
  client/src/components/Comment/CommentList.tsx
  client/src/components/Comment/index.tsx
  client/src/components/Review.tsx
  client/src/components/common/Nav.tsx
  client/src/components/editor/Editor.tsx
  client/src/components/editor/LineBlock/EditLineBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlockReadonly.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ProductCard.tsx
  client/src/components/editor/common/Button.tsx
  client/src/components/editor/common/Input.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/ScrollToTop.tsx
  client/src/components/product/ProductCard.tsx
  client/src/components/product/ProductDetailPost.tsx
  client/src/components/product/ProductLink.tsx
  client/src/components/product/ProductReview.tsx
  client/src/components/profile/Profile.tsx
  client/src/components/profile/ProfileBar.tsx
  client/src/modules/editor.ts
  client/src/modules/images.ts
  client/src/modules/users.ts
  client/src/pages/Main.tsx
  client/src/pages/Post.tsx
  client/src/pages/Product.tsx
  client/src/pages/User.tsx
  client/src/pages/Write.tsx
  client/src/type/product.ts
  client/src/type/user.ts
Labels: 새 기능, 프론트엔드

#47 fix: 리뷰 작성, 프로필 이미지 등의 잔버그
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/upload.ts
  client/src/components/Review.tsx
  client/src/components/Search.tsx
  client/src/components/common/Nav.tsx
  client/src/components/editor/Editor.tsx
  client/src/components/editor/LineBlock/EditLineBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlockReadonly.tsx
  client/src/components/editor/Menu/SelectMenu.tsx
  client/src/components/layout/Header.tsx
  client/src/components/product/ProductLink.tsx
  client/src/components/profile/Profile.tsx
  client/src/pages/Main.tsx
  client/src/pages/Product.tsx
  client/src/pages/User.tsx
  client/src/pages/UserPage.tsx
  client/src/pages/Write.tsx
Labels: 새 기능, 프론트엔드

#54 무한 스크롤 및 기타
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/product.ts
  client/src/api/upload.ts
  client/src/components/Review.tsx
  client/src/components/main/contents/initpostlist.tsx
  client/src/components/main/contents/initpostlistinfinity.tsx
  client/src/components/store/contents/initproductlist.tsx
  client/src/components/store/contents/initproductlistinfinity.tsx
  client/src/pages/Login.tsx
  client/src/pages/Main.tsx
  client/src/pages/Store.tsx
  client/src/pages/Styling.tsx
Labels: 새 기능, 프론트엔드

#55 fix: 상품 페이지 subThumbnail 자세히 보기 & 에디터 이미지 업로드 후 focus & 반응형 페이지
  client/src/api/product.ts
  client/src/api/upload.ts
  client/src/api/users.ts
  client/src/assets/DESKIT.png
  client/src/components/Comment/CommentList.tsx
  client/src/components/Review.tsx
  client/src/components/common/Nav.tsx
  client/src/components/editor/Editor.tsx
  client/src/components/editor/LineBlock/EditLineBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlock.tsx
  client/src/components/editor/LineBlock/ImageLineBlock/ImageBlockReadonly.tsx
  client/src/components/editor/Menu/SelectMenu.tsx
  client/src/components/main/contents/initpostlist.tsx
  client/src/components/main/contents/initpostlistinfinity.tsx
  client/src/components/product/ProductCard.tsx
  client/src/components/product/ProductLink.tsx
  client/src/components/store/contents/initproductlist.tsx
  client/src/components/store/contents/initproductlistinfinity.tsx
  client/src/modules/images.ts
  client/src/pages/Post.tsx
  client/src/pages/Product.tsx
  client/src/pages/Signup.tsx
  client/src/pages/Store.tsx
  client/src/pages/Styling.tsx
  client/src/pages/User.tsx
  client/src/pages/Write.tsx
  client/src/type/product.ts
Labels: 버그, 새 기능, 프론트엔드
